// Code generated by entc, DO NOT EDIT.

package sysuser

const (
	// Label holds the string label denoting the sysuser type in the database.
	Label = "sys_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the sysuser in the database.
	Table = "sys_users"
)

// Columns holds all SQL columns for sysuser fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
