// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SysRole is the predicate function for sysrole builders.
type SysRole func(*sql.Selector)

// SysUser is the predicate function for sysuser builders.
type SysUser func(*sql.Selector)
