// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (

	"github.com/wanhello/omgind/internal/api/v2"
	"github.com/wanhello/omgind/internal/app/module/adapter"
	"github.com/wanhello/omgind/internal/app/service.ent"
	"github.com/wanhello/omgind/internal/router"
	"github.com/wanhello/omgind/internal/schema/repo_ent"

	_ "github.com/jackc/pgx/v4/stdlib"
	_ "github.com/wanhello/omgind/internal/app/swagger"

)

// Injectors from wire.go:

// BuildInjector 生成注入器
func BuildInjector() (*Injector, func(), error) {

	auther, cleanup, err := InitAuth()
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := InitEntClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	role := &repo_ent.Role{
		EntCli: client,
	}
	roleMenu := &repo_ent.RoleMenu{
		EntCli: client,
	}
	menuActionResource := &repo_ent.MenuActionResource{
		EntCli: client,
	}
	user := &repo_ent.User{
		EntCli: client,
	}
	userRole := &repo_ent.UserRole{
		EntCli: client,
	}
	casbinAdapter := &adapter.CasbinAdapter{
		RoleModel:         role,
		RoleMenuModel:     roleMenu,
		MenuResourceModel: menuActionResource,
		UserModel:         user,
		UserRoleModel:     userRole,
	}
	syncedEnforcer, cleanup3, err := InitCasbin(casbinAdapter)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dict := &repo_ent.Dict{
		EntCli: client,
	}
	dictItem := &repo_ent.DictItem{
		EntCli: client,
	}
	service_entDict := &service_ent.Dict{
		DictModel:     dict,
		DictItemModel: dictItem,
	}
	api_v2Dict := &api_v2.Dict{
		DictSrv: service_entDict,
	}
	demo := &repo_ent.Demo{
		EntCli: client,
	}
	service_entDemo := &service_ent.Demo{
		DemoModel: demo,
	}
	api_v2Demo := &api_v2.Demo{
		DemoSrv: service_entDemo,
	}
	menu := &repo_ent.Menu{
		EntCli: client,
	}
	menuAction := &repo_ent.MenuAction{
		EntCli: client,
	}
	service_entMenu := &service_ent.Menu{
		MenuModel:               menu,
		MenuActionModel:         menuAction,
		MenuActionResourceModel: menuActionResource,
	}
	api_v2Menu := &api_v2.Menu{
		MenuSrv: service_entMenu,
	}
	service_entRole := &service_ent.Role{
		Enforcer:      syncedEnforcer,
		RoleModel:     role,
		RoleMenuModel: roleMenu,
		UserModel:     user,
	}
	api_v2Role := &api_v2.Role{
		RoleSrv: service_entRole,
	}
	service_entUser := &service_ent.User{
		Enforcer:      syncedEnforcer,
		UserModel:     user,
		UserRoleModel: userRole,
		RoleModel:     role,
	}
	api_v2User := &api_v2.User{
		UserSrv: service_entUser,
	}
	cmdable, cleanup4, err := InitRedisCli()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	vcode := InitVcode(cmdable)
	signIn := &service_ent.SignIn{
		Auth:            auther,
		UserModel:       user,
		UserRoleModel:   userRole,
		RoleModel:       role,
		RoleMenuModel:   roleMenu,
		MenuModel:       menu,
		MenuActionModel: menuAction,
		Vcode:           vcode,
	}
	api_v2SignIn := &api_v2.SignIn{
		SigninSrv: signIn,
		Vcode:     vcode,
	}
	routerRouter := &router.Router{
		Auth:           auther,
		CasbinEnforcer: syncedEnforcer,
		DictApiV2:      api_v2Dict,
		DemoAPIV2:      api_v2Demo,
		MenuAPIV2:      api_v2Menu,
		RoleAPIV2:      api_v2Role,
		UserAPIV2:      api_v2User,
		SignInAPIV2:    api_v2SignIn,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine:         engine,
		Auth:           auther,
		CasbinEnforcer: syncedEnforcer,
		MenuSrv:        service_entMenu,
		RedisCli:       cmdable,
	}
	return injector, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
