version: "3.7"

services:
  go:
    container_name: omgind-server

#    build:
#      context: ./
#      dockerfile: ./dev/Dockerfile.dev

#    entrypoint: /app/run.sh

    image: omgind:latest
    restart: always
    environment:
      - GOPROXY=https://goproxy.cn,direct

    ports:
      - "10088:10088"
    volumes:
      - $PWD:/app/omgind
      - $PWD/deploy/dev/run.sh:/app/run.sh

    working_dir: /app/omgind
    # command: 
    #   - "go run /go/omgind/cmd/omgind/main.go web -c /go/omgind/configs/config.toml -m /go/omgind/configs/model.conf --menu /go/omgind/configs/menu.yaml"
    #   - /bin/bash

    depends_on:
      - redis
      - mysql

    networks:
      - omgind

  redis:
    container_name: omgind-redis
    image: "redis:alpine"
    restart: always
    ports:
      - "16739:6739"

    networks:
      - omgind

  mysql:
    container_name: omgind-mysql
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: omgind
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: omgind
      MYSQL_PASSWORD: 123456
    volumes:
      -  $PWD/data/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    ports:
      - "13306:3306"
    
    networks:
      - omgind

networks:
  omgind:
    driver: bridge
    name: omgind
